version: '3.9'

services:
  docker-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 50s
      retries: 3
    restart: on-failure
    volumes:
      - docker_mysql:/var/lib/mysql


  authentication-service:
    container_name: authentication_service
    image: gyawalirajiv/swa-authentication-service
    ports:
      - 8080:8080
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: docker-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: swa
      MYSQL_PORT: 3306
    depends_on:
      docker-mysql:
        condition: service_healthy


  catalog-service:
    container_name: catalog_service
    image: gyawalirajiv/swa-catalog-service
    ports:
      - 8081:8081
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    environment:
      STOCK_SERVICE_URL: stock-service
      MYSQL_URL: docker-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: swa
      MYSQL_PORT: 3306
    depends_on:
      docker-mysql:
        condition: service_healthy

  stock-service:
    container_name: stock_service
    image: gyawalirajiv/swa-stock-service
    ports:
      - 8082:8082
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: docker-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: swa
      MYSQL_PORT: 3306
    depends_on:
      docker-mysql:
        condition: service_healthy

volumes:
  docker_mysql: