spring:
  application:
    name: stock-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swa?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082

app:
  security:
    jwt:
      secret: secret
      expiry: 100000