apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-app
    ports:
      - port: 80
        nodePort: 30070
        targetPort: 8070
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
        - name: authentication-app
          image: authentication-service
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              values: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: auth_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: auth_dbName

            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-secret
                  key: secret

            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: database-secret
                  key: root

            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: database-secret
                  key: password
          imagePullPolicy: Never