apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-app
  ports:
    - port: 80
      nodePort: 30070
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
        - name: authentication-app
          image: gyawalirajiv/swa-authentication-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: auth_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: auth_dbName

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key

            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
