apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock-app
  ports:
    - port: 80
      nodePort: 30087 # exposing to local, to access this service
      targetPort: 8082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
        - name: stock-app
          image: gyawalirajiv/swa-stock-service
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: stock_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: stock_dbName
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
          imagePullPolicy: IfNotPresent